name: Markdown Auto Translator

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**.md"

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 #이전 커밋 히스토리를 모두 가져와서 diff가 가능하게 끔.

      - name: Send markdown to Translator API
        run: |
          #현재 커밋(HEAD)과 바로 이전 커밋(HEAD~) 사이에서 변경된 마크다운 파일을 찾기.
          CHANGED_FILE=$(git diff --name-only HEAD~1 HEAD | grep '^docs/.*\.md$' | head -n 1)

          if [ -z "$CHANGED_FILE" ]; then
            echo "번역할 마크다운 파일 변경점을 찾지 못함."
            exit 0
          fi

          echo "디텍팅된 파일: $CHANGED_FILE"

          #파일 내용 읽기
          ORIGINAL_TEXT=$(cat "$CHANGED_FILE")

          #내 ngrok 주소 세팅
          API_URL="https://favoring-baggage-goldfish.ngrok-free.dev/api/v1/translate"

          #API 서버로 전송
          RESPONSE=$(curl -s -X POST "$API_URL" \
            -H "Content-Type: application/json" \
            -d "{\"markdown_text\": \"$ORIGINAL_TEXT\", \"target_language\": \"Korean\"}")

          echo "서버 응답 결과: $RESPONSE"
